[rom_paths]
3do = ""
adam = ""
ags = ""
amiga = ""
amiga1200 = ""
amiga600 = ""
amigacd32 = ""
amstradcpc = ""
android = ""
androidapps = ""
androidgames = ""
apple2 = ""
apple2gs = ""
arcade = ""
arcadia = ""
archimedes = ""
arduboy = ""
astrocde = ""
atari2600 = ""
atari5200 = ""
atari7800 = ""
atari800 = ""
atarijaguar = ""
atarijaguarcd = ""
atarilynx = ""
atarist = ""
atarixe = ""
atomiswave = ""
bbcmicro = ""
c64 = ""
cdimono1 = ""
cdtv = ""
chailove = ""
channelf = ""
coco = ""
colecovision = ""
consolearcade = ""
cps = ""
cps1 = ""
cps2 = ""
cps3 = ""
crvision = ""
daphne = ""
desktop = ""
doom = ""
dos = ""
dragon32 = ""
dreamcast = ""
easyrpg = ""
electron = ""
emulators = ""
epic = ""
famicom = ""
fba = ""
fbneo = ""
fds = ""
flash = ""
fm7 = ""
fmtowns = ""
fpinball = ""
gamate = ""
gameandwatch = ""
gamecom = ""
gamegear = ""
gb = ""
gba = ""
gbc = ""
gc = ""
genesis = ""
gmaster = ""
gx4000 = ""
intellivision = ""
j2me = ""
kodi = ""
laserdisc = ""
lcdgames = ""
lowresnx = ""
lutris = ""
lutro = ""
macintosh = ""
mame = ""
mame-advmame = ""
mark3 = ""
mastersystem = ""
megacd = ""
megadrive = ""
megaduck = ""
mess = ""
model2 = ""
model3 = ""
moto = ""
msx = ""
msx1 = ""
msx2 = ""
msxturbor = ""
mugen = ""
multivision = ""
n3ds = ""
n64 = ""
n64dd = ""
naomi = ""
naomi2 = ""
naomigd = ""
nds = ""
neogeo = ""
neogeocd = ""
nes = ""
ngage = ""
ngp = ""
ngpc = ""
odyssey2 = ""
openbor = ""
oric = ""
palm = ""
pc = ""
pc88 = ""
pc98 = ""
pcarcade = ""
pcengine = ""
pcenginecd = ""
pcfx = ""
pico8 = ""
plus4 = ""
pokemini = ""
ports = ""
ps2 = ""
ps3 = ""
ps4 = ""
psp = ""
psvita = ""
psx = ""
pv1000 = ""
quake = ""
samcoupe = ""
satellaview = ""
saturn = ""
scummvm = ""
scv = ""
sega32x = ""
segacd = ""
sfc = ""
sg-1000 = ""
sgb = ""
snes = "/home/onur"
solarus = ""
spectravideo = ""
steam = ""
stv = ""
sufami = ""
supergrafx = ""
supervision = ""
supracan = ""
switch = ""
symbian = ""
tanodragon = ""
tg-cd = ""
tg16 = ""
ti99 = ""
tic80 = ""
to8 = ""
triforce = ""
trs-80 = ""
type-x = ""
uzebox = ""
vectrex = ""
vic20 = ""
videopac = ""
vircon32 = ""
virtualboy = ""
vpinball = ""
vsmile = ""
wasm4 = ""
wii = ""
wiiu = ""
windows = ""
windows3x = ""
windows9x = ""
wonderswan = ""
wonderswancolor = ""
x1 = ""
x68000 = ""
xbox = ""
xbox360 = ""
xboxone = ""
zmachine = ""
zx81 = ""
zxnext = ""
zxspectrum = ""
